apiVersion: skaffold/v1beta13
kind: Config
build:
  artifacts:
    - image: products-backend
      context: src/backend
    - image: products-frontend
      context: src/frontend
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:latest"
test:
  - image: products-backend:latest
    structureTests:
    - ./src/backend/tests/structure_test.yaml
deploy: {}

profiles:
  - name: local
    deploy:
      kustomize:
          path: deploy/overlays/local
          flags:
            global:
            - '-n=dev'
    activation:
    - env: ENV=local
    - kubeContext: minikube
      command: dev
  - name: local-postgres
    deploy:
      kustomize:
          path: deploy/overlays/local-postgres
          flags:
            global:
            - '-n=dev'
  - name: staging
    activation:
    - env: ENV=staging
    - kubeContext: gke_kubernetes-cicd-246207_australia-southeast1-a_kubernetes-cicd
      command: dev
    build:
      artifacts:
        - image: gcr.io/kubernetes-cicd-246207/dev/backend
          context: src/backend
        - image: gcr.io/kubernetes-cicd-246207/dev/frontend
          context: src/frontend
      tagPolicy:
        envTemplate:
          template: "{{.IMAGE_NAME}}:latest"
    deploy:
      kustomize:
          path: deploy/overlays/staging
          flags:
            global:
            - '-n=np'
  - name: production
    deploy:
      kustomize:
          path: deploy/overlays/production
          flags:
            global:
            - '-n=prod'
  - name: production-full
    build:
      artifacts:
        - image: gcr.io/kubernetes-cicd-246207/prod/backend
          context: src/backend
        - image: gcr.io/kubernetes-cicd-246207/prod/frontend
          context: src/frontend
      tagPolicy:
        envTemplate:
          template: "{{.IMAGE_NAME}}:latest"
    deploy:
      kustomize:
          path: deploy/overlays/production
          flags:
            global:
            - '-n=prod'
  - name: prod-postgres
    build: {}
    deploy:
      kustomize:
        path: deploy/postgres/overlays/production-with-namespace
        flags:
          global:
          - '-n=prod'
  - name: ci-postgres
    build: {}
    deploy:
      kustomize:
        path: deploy/postgres/overlays/ci
        flags:
          global:
          - '-n=tekton-pipelines'

