apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: backend-ci-binding-admin
  namespace: tekton-pipelines
subjects:
  - kind: ServiceAccount
    name:  backend-ci-binding-admin
    namespace: default
roleRef:
  kind: ClusterRole
  name:  backend-ci-binding-admin
  apiGroup: rbac.authorization.k8s.io