kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: backend-ci-binding-admin
  namespace: tekton-pipelines
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces", "secrets", "events", "serviceaccounts", "configmaps"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
  - apiGroups: ["apps"]
    resources: ["statefulsets", "deployments"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
  - apiGroups: ["tekton.dev"]
    resources: ["tasks", "clustertasks", "taskruns", "pipelines", "pipelineruns", "pipelineresources"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
  - apiGroups: ["tektonexperimental.dev"]
    resources: ["tektonlisteners", "eventbindings"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
---